import type { Metadata } from "next";
import Link from "next/link";
import { ArrowIcon, CheckIcon } from "@/components/icons";
import { playStoreUrl, product } from "@/data/product";

export const metadata: Metadata = { title: "Download Fileio for Android", description: "Download Fileio: File Manager & Scanner for Android from Google Play.", alternates: { canonical: "/download" } };

export default function DownloadPage() {
  return <section className="bg-[linear-gradient(180deg,#f8fbff,#fff)] py-20 sm:py-28"><div className="page-shell grid items-center gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">Available for Android</p><h1 className="mt-4 text-5xl font-bold leading-tight tracking-[-0.05em] text-slate-950 sm:text-6xl">Get Fileio on Google Play.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Download {product.storeName} to manage files, view supported documents, and scan paper documents to PDF.</p><a href={playStoreUrl} className="button-primary mt-8" target="_blank" rel="noopener noreferrer">Open Google Play <ArrowIcon /></a><p className="mt-4 text-xs text-slate-500">Package: {product.packageName}</p></div><div className="card p-7 sm:p-9"><div className="flex items-center gap-4"><span className="grid size-14 place-items-center rounded-2xl bg-blue-600 text-white"><svg aria-hidden="true" className="size-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7"><path d="M5 7.5A2.5 2.5 0 0 1 7.5 5h3l2 2h4A2.5 2.5 0 0 1 19 9.5v7A2.5 2.5 0 0 1 16.5 19h-9A2.5 2.5 0 0 1 5 16.5v-9Z" strokeLinecap="round" strokeLinejoin="round" /></svg></span><div><h2 className="text-xl font-semibold text-slate-950">{product.storeName}</h2><p className="mt-1 text-sm text-slate-500">by JonnyLab</p></div></div><div className="mt-8 space-y-4 border-t border-slate-200 pt-7">{["File manager and search", "PDF, DOCX, XLSX, PPTX, JPG, and PNG viewer", "PDF document scanner", "Optional read-only cloud access for Pro users"].map((item) => <p key={item} className="flex items-start gap-3 text-sm text-slate-600"><span className="mt-0.5 text-blue-600"><CheckIcon /></span>{item}</p>)}</div><p className="mt-8 rounded-xl bg-slate-50 p-4 text-xs leading-5 text-slate-500">The Google Play listing may not be publicly available until the app release is live.</p></div></div><div className="page-shell mt-14 text-sm text-slate-500">Want to learn first? <Link href="/guides" className="font-semibold text-blue-700">Browse Fileio guides</Link>.</div></section>;
}
