import type { Metadata } from "next";

export const metadata: Metadata = { title: "Privacy", description: "Basic privacy information for the Fileio Android app and website.", alternates: { canonical: "/privacy" } };

export default function PrivacyPage() {
  return <LegalPage title="Privacy" updated="June 30, 2026"><p>Fileio is designed primarily for managing and viewing files on your Android device. You do not need to create a Fileio account to use local file management features.</p><h2>Local files</h2><p>Fileio accesses files and folders only when Android permissions allow it. Local file actions—such as browsing, searching, renaming, deleting, sharing, viewing, and scanning—take place at your direction.</p><h2>Optional cloud connections</h2><p>Google Drive and Dropbox connections are optional Pro features. If you choose to connect one of these services, Fileio uses the connection to browse folders and open supported files. Cloud access is read-only: Fileio does not upload, modify, delete, or sync files in your cloud account.</p><h2>Website</h2><p>This product website may receive basic technical information normally sent when a webpage is requested, such as browser type and request logs, through its hosting provider. Do not send sensitive personal information through the website.</p><h2>Your choices</h2><p>You can use local file features without connecting a cloud account. You can also disconnect a cloud provider through the available app or provider settings.</p><h2>Updates</h2><p>We may update this page when the app or website changes. The date above shows the latest revision.</p><h2>Contact</h2><p>For privacy questions, contact JonnyLab through the support contact shown on the Fileio Google Play listing.</p></LegalPage>;
}

function LegalPage({ title, updated, children }: { title: string; updated: string; children: React.ReactNode }) { return <section className="page-shell py-16 sm:py-24"><div className="mx-auto max-w-3xl"><p className="eyebrow">Fileio</p><h1 className="section-title mt-4">{title}</h1><p className="mt-3 text-sm text-slate-500">Last updated: {updated}</p><div className="article-body mt-10 border-t border-slate-200 pt-10">{children}</div></div></section>; }
